### ISSUE TITLE
Jumbled SVG font

### ISSUE THREAD

**Issue by mavit** [googlefonts/nanoemoji#113]
I tried to build an SVG font with `nanoemoji --color_format=picosvgz ...`.  When used with Firefox, I found that the images were shuffled into the wrong characters.

```html
<!DOCTYPE html>
<html>
	<body>
		U+1F600 Grinning Face
		
		<p>Default font: 😀</p>
		<p>SVG font: <span style="font-family: An Emoji Family;">😀</span></p>
	</body>
</html>
```

![image](https://user-images.githubusercontent.com/120296/90885166-00c35180-e3a9-11ea-87a9-1bee19dd3fa7.png)

**Comment by anthrotype** [comment]
@mavit Sorry for the radio silence, I'm back on this.
You said "when used in Firefox" -- does it only happen there, or also on other browsers, say, Chrome?

Can you give me a link to the SVG sources and the exact command you run so I can try to reproduce this? Thank you

**Comment by mavit** [comment]
> @mavit Sorry for the radio silence, I'm back on this.
> You said "when used in Firefox" -- does it only happen there, or also on other browsers, say, Chrome?

I tried Firefox because I'm not sure I have anything else that supports SVG fonts.  Fedora's build of Chromium leaves a blank square where the emoji should be.

> Can you give me a link to the SVG sources and the exact command you run so I can try to reproduce this? Thank you

```bash
git clone git://github.com/hfg-gmuend/openmoji.git
nanoemoji --color_format=picosvg ./openmoji/color/svg/*.svg
```

**Comment by anthrotype** [comment]
ah you're right, Chrome doesn't support OT-SVG yet. I think Safari on Mac does, as should do the Adobe design apps.
Anyway, thanks for the reproducer -- I'll look into this soon.

**Comment by anthrotype** [comment]
Ah I see what's going on here. With --color_format=picosvg (or picosvgz) we try to group reused shapes across input SVGs and create a single SVG document in the OT-SVG table so we can reference the shared shapes. When muiltiple glyphs are defined in the same OT-SVG document, these need to be sorted so that members of the same reuse group have contiguous glyph indexes. We do that in `_ensure_groups_grouped_in_glyph_order` function in `nanoemoji.svg` module. 
https://github.com/googlefonts/nanoemoji/blob/f4f36096e9be2b655af530ae5672296a9dc62a8c/src/nanoemoji/svg.py#L152-L165

The problem is that this function is changing the TTFont glyph order (reshuffling glyphs around) but the cmap and GSUB tables are not re-compiled but they still use the old, and now incorrect, glyph indexes. Hence the text is all jumbled, because the wrong glyphs are mapped in cmap and the wrong glyphs are substituted in GSUB.

I have a WIP patch where I make sure that cmap and GSUB are fully decompiled before the glyph order is modified so that by the time the updated font is compiled, the cmap and GSUB will be compiled with the new glyph indexes.
