### ISSUE TITLE
Ligature changed from rlig feature to ccmp

### ISSUE THREAD

**Issue by yisibl** [googlefonts/nanoemoji#279]
Different platforms or browsers have some differences in ligature support([Test](http://unifraktur.sourceforge.net/testcases/enable_opentype_features/)). Let us discuss what issues should be paid attention to in emoji ligatures.

noto-emoji and noto-emoji-svg both use ccmp by default

https://github.com/googlefonts/noto-emoji/blob/41ae6686ace1453b432ac907a165428f2e1ad54e/NotoColorEmoji.tmpl.ttx.tmpl#L311

https://github.com/adobe-fonts/noto-emoji-svg/blob/ed5c78c8e3d46fdf8dbf7532875aaabfdcdc5c3a/GSUB.fea#L4

**Comment by anthrotype** [comment]
first should identify the issue, only then propose a solution

**Comment by anthrotype** [comment]
it turns out NotoColorEmoji.ttf (the CBLC/CBDT color font from Google) uses "ccmp", not "rlig" for its ligature substitutions, see:  https://github.com/googlefonts/noto-emoji/blob/41ae6686ace1453b432ac907a165428f2e1ad54e/NotoColorEmoji.tmpl.ttx.tmpl#L311

to be on the safe side, we should probably do the same in nanoemoji
