### ISSUE TITLE
Test roundtrip svg:colrv1:svg

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/nanoemoji#3]

**Comment by anthrotype** [comment]
A few notes so that I'll remember when pick this up again next week.

For converting COLRv1 linear gradient paints to SVG linearGradient elements, we need to
- transform linear gradient point coordinates from EM font units to SVG space;
- `p0` becomes `(x1,y1)` and `p2` (not `p1`) becomes `(x2,y2)`; no need to set `gradientTransform`; the way we currently encode p0, p1, and p2 makes p1 redundant, as p2 is already sitting on the "frontline" of the linear gradient (which intersects p1 and is perpendicular to the transformed linear gradient direction). Since this is meant to roundtrip ourselves for the sake of testing, more than a general way to convert COLRv1 to SVG, this is fine for now.
- the ColorLine stops are simply encoded as stop elements, with offsets encoded as floats 0..1, stop-color with named or hex-formatted colors, optionally stop-opacity.

For converting COLRv1 radial gradient paints to SVG radialGradient elements, we need to
- compute the radialGradient's `gradientTransform` attribute, by taking the matrix product of the COLRv1 `Affine2x2` (implicitly padded with dx=0, dy=0) and the EM-square-to-SVG-viewbox;
- compute the inverse of gradientTransform, and map `c0` and `c1` points (centres of the ellipses) with this inverse matrix (to counteract the effect of gradientTransform so that the centres will go back to where they were once gradientTransform is applied to them upon rendering the svg); thus transformed `c0` and `c1` will become, respectively, the radialGradient's `(fx, fy)` and `(cx, cy)`;
- the `r0` and `r1` can be written as is into `fr` and `r` attributes.

**Comment by anthrotype** [comment]
Fixed by #81
